#!/bin/bash

##
# Sends a Slack webhook containing a list of all
# the JIRA tickets since the last tagged version.
##

# Config
product_name=${PRODUCT_NAME:-Product}
timestamp=`date +%s`
slack_webhook_url="$SLACK_WEBHOOK_URL"
tmp_filename="tmp-jira-tickets-$timestamp.txt"

# Get the number of commits since last tag
prev_tag=`git rev-list --tags --no-walk --max-count=1`
echo 'previous tag: '.$prev_tag
num_commits=`git rev-list $prev_tag..HEAD --count`
echo 'check last '.$num_commits.'commits'

# Get a list of all the JIRA tickets since
git log --pretty=format:"%s" -n $num_commits \
    | grep -o [A-Z]+-[0-9]+ -E \
    | sort -t: -u -k1,1 \
    | while read -r t ; do echo -e "• $t (https://$JIRA_PREFIX.atlassian.net/browse/$t)" >> $tmp_filename ; done

empty_message=''
if [ ! -f "$tmp_filename" ]; then
  echo 'No JIRA tickets detected since last commit with tag.'
  empty_message='No JIRA tickets detected since last commit with tag.'
fi

# Send a Slack webhook
header="*$product_name* deploy completed!\n\nJIRA Tickets Mentioned:"
payload=`< $tmp_filename sed '/^[ \t]*$/d' | paste -sd "\\n" -`

echo `$header\n$payload $empty_message`

curl -X POST --data-urlencode "payload={\"text\": \"$header\n$payload $empty_message\"}" $slack_webhook_url

