#!/bin/bash

##
# Sends a Slack webhook containing a list of all
# the JIRA tickets since the last tagged version.
##

# Config
product_name=${PRODUCT_NAME:-Product}
timestamp=`date +%s`
slack_webhook_url="$SLACK_WEBHOOK_URL"
github_workspace="$GITHUB_WORKSPACE"
tmp_filename="tmp-jira-tickets-$timestamp.txt"

echo "github_workspace: $github_workspace"

git --version
git config --global --add safe.directory /github/workspace
git config user.name "GitHub Actions Bot"
git config user.email "<>"
git status
git tag
git describe

list_tag=`git rev-list --tags`
echo "list tags: $list_tag"

# Get the number of commits since last tag
prev_tag=`git rev-list --tags --no-walk --max-count=1`
echo "previous tag: $prev_tag"
num_commits=`git rev-list $prev_tag..HEAD --count`
echo "check last $num_commits commits"

# Get a list of all the JIRA tickets since
git log --pretty=format:"%s" -n $num_commits \
    | grep -o [A-Z]+-[0-9]+ -E \
    | sort -t: -u -k1,1 \
    | while read -r t ; do echo -e "• $t (https://$JIRA_PREFIX.atlassian.net/browse/$t)" >> $tmp_filename ; done

payload=''
if [ ! -f "$tmp_filename" ]; then
  echo 'No JIRA tickets detected since last commit with tag.'
  payload='>No JIRA tickets detected since last commit with tag.'
else
  payload=`< $tmp_filename sed '/^[ \t]*$/d' | paste -sd "\\n" -`
fi

# Send a Slack webhook
header="> *$product_name* deploy completed"

echo "$header\n$payload"

curl -X POST --data-urlencode "payload={\"text\": \"$header\n$payload $empty_message\"}" $slack_webhook_url

